source 'http://ruby.taobao.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.13'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.2'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'colorize'
#-------------Test Gems-------------
#html content extractor
gem 'ruby-readability', :require => 'readability'

#cancancan
gem 'cancancan', '~> 1.10'
gem 'devise', '~> 3.5.1'

#image generate
gem 'imgkit'
gem 'wkhtmltoimage-binary'
gem 'sidekiq'
gem 'sinatra', :require => nil
gem 'unicorn'
gem 'guid'
gem 'nokogiri'
# 这个也不错，但是要使用浏览器，应该是可以不使用浏览器的
gem 'watir-webdriver'

gem "capybara"
gem "capybara-webkit"
gem "poltergeist"
